#!/bin/bash
###############################################################################
# Script Name  : z-ytdlupdate
# Description  : Updates youtube-dl automatically using anacron
# Dependencies : anacron, sed
# Arguments    : None
# Author       : Richard B. Romig, 18 July 2019
# Email        : rick.romig@gmail.com
# Comments     : /etc/cron.daily /etc/cron.weekly /etc/cron.monthly
# Last updated : 16 Jul 2020
###############################################################################

set -e

LOG_FILE="/var/log/ytdlup.log"

echo "$(date): $(youtube-dl -U)" >> "$LOG_FILE" 2>&1

LOG_LEN=$(wc -l "$LOG_FILE" | awk '{ print $1 }')
(( LOG_LEN > 30 )) && sed -i '1d' "$LOG_FILE"
LINE_ONE=$(sed -n '1p' "$LOG_FILE" | grep 'Updated')
[ -n "$LINE_ONE" ] && sed -i '1d' "$LOG_FILE"

exit
